language: python
os: linux
dist: xenial

cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.cargo"
    - "target"
    - ".tox"

branches:
  only:
  - master
  - "/^v.*$/"

script: tox

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustc -V

before_script: pip install tox-travis

jobs:
  allow_failures:
    - name: integration (ipfs/redis)
  include:
    - &check
      stage: check # do a pre-screen to make sure this is even worth testing
      python: 3.7

    - &test
      stage: test
      python: 2.7
    - <<: *test
      os: osx
      language: generic
      env:
        - TOXENV=py36
    - <<: *test
      python: 3.7
      name: integration (ipfs/redis)
      before_install:
        - sudo snap install ipfs
        - "/snap/bin/ipfs --version"
        - "/snap/bin/ipfs daemon --init --offline &>/dev/null &"
      services:
        - redis-server
        - docker
    - <<: *test
      python: 3.6
    - <<: *test
      python: 3.5
    - <<: *test
      name: wasm-pack
      language: rust
      rust: stable
      before_script: skip
      script:
        - rustup target add wasm32-unknown-unknown
        - cargo install --force wasm-pack
        - wasm-pack build

    - &wheel
      stage: build wheel and send to github releases
      python: 3.7
      services:
        - docker
      env:
        - PIP=pip
        - CIBW_BUILD='cp37-*'
        - CIBW_SKIP='*-manylinux1_i686'
        - CIBW_BEFORE_BUILD_LINUX='source .travis/install_cargo.sh'
        - CIBW_ENVIRONMENT_LINUX='PATH="$HOME/.cargo/bin:$PATH"'
      before_script: skip
      script:
        - sudo $PIP install cibuildwheel==0.10.2
        - cibuildwheel --output-dir wheelhouse
      deploy:
        provider: releases
        api_key:
          secure: "QQAs4MABWzFAVaf85f4KlQ5eFl2/LXEk3yiuIbNNhwYNtWBjsQG9lkcPNE3ZeYJS+eM37xrob6Ca0ugIYdWtiFz++sXMpIr4UP4YWDcdnLct2fUXVKVspX4Rfk2Nqctjz9NmKUQaNNatFtE07dGHKIdKmX7wLzT9y05zeBLr+LwpPnsjbdnncxLczs+Ee+zKQutJiPveoM8S1UMmCDVr5JcIx1MgVc7+2XADiYtw52lXmDN4HnBk8e/NVNe4wuAK2uxYqiwqD5PZJ+/QkU0o+DJ7GXPksguiu6LGymKIkpQCRaF2SBJkgzUTkHB9OMmCPL+NAK/wxRB2H/jHoGOoFkh/Mh7kwKxGe731l/sKcVn6+lUEMvxiroPGA2jlgkPhaZItsDr4N+uVc1w5J6clgZ6RvnByVwsvzO5KzHR9tPW0r+p/CG3PFWiaC85+99RpZ+Nkx/zwHJf4LBjKkpUoBkGlhSEnJpZdxWPV32qHJer3wtl40Z/uesVwcSiMz6yBVuoc6R6NfIyUNeDIliEh6j/SF+aeR9E7G9p60ZBdW7tsFw1MAiS7H5g7SVSJOMc5CguKt7xyO8J8yeaM0c4MD+roWnIX0fYSp3V3wg7urkU2gc2SyAeg1xFOtrv/Tv8snO2S4ZgLUbilMwF7ZUzhf/hJzmfntKfxrqFitMc75Bw="
        file_glob: true
        file: wheelhouse/sourmash*.whl
        skip_cleanup: true
        on:
          tags: true
    - <<: *wheel
      os: osx
      osx_image: xcode10.1
      language: generic
      before_script:
        - sudo $PIP install -U pip setuptools
      env:
        - PIP=pip2
        - CIBW_BUILD='cp37-*'
        - CIBW_ENVIRONMENT_MACOS='MACOSX_DEPLOYMENT_TARGET=10.11'

stages:
  - check
  - test
  - wheel
