language: python

cache:
  directories:
    - $HOME/.cache/pip

branches:
  only:
  - master
  - "/^v.*$/"

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"

dist: xenial

script: tox

install: pip install tox-travis

jobs:
  include:
    - &check
      stage: check # do a pre-screen to make sure this is even worth testing
      os: linux
      python: '3.7'
    - &test
      stage: test
    - <<: *test
      os: osx
      language: generic
      before_install:
        - brew update
        - brew outdated python || brew upgrade python
      env:
        - TOXENV=py37
    - <<: *test
      name: IPFS and Redis integration
      os: linux
      dist: xenial
      python: '3.7'
      install:
        - pip install tox-travis
        - sudo snap install ipfs
      services:
        - redis-server
        - docker
      script:
        - "/snap/bin/ipfs daemon --init --offline &>/dev/null &"
        - tox
    - &wheel
      stage: build wheel and send to github releases
      services:
        - docker
      env:
        - PIP=pip
        - CIBW_SKIP='*-manylinux1_i686'
      script:
        - $PIP install cibuildwheel==0.10.0
        - cibuildwheel --output-dir wheelhouse
      deploy:
        provider: releases
        api_key:
          secure: CTO7kiWKLper/nJU093pp796P6MhV2IPz4M2Ws0//YOqU2gKZalyGmAdJtqsFk0+eZthnOp0GQzuSJYpN0+jOx3IU+SInnMg7HdLooyfLxgjDri9xOMBtTiCzSbY77NnLKNk4Nj8idb3Gfjp0F+/5TIRlpInTZ7iYGoG1ZYM/kCyBiTkzDd8tO1LBKhWBad3h3bv099OcmoYT7GETuS9LMmUYJLOe/aotOfOhSttNxYIIIY2RmjFQjWBZCAWPx9P8PnTdhDmrMQL9kRBz+z9/E+ikaaMgtx9QTsF75mZn1qix0+a0LwvRaXKCzYCZ7KGUaSs/npIrBbtXxxA7wK4GFTGb2ERpJOzp4MGzwLiToQlNOHZ48F2N3RgQVL0v+rfvGjt14csWRA21jfrvP2yk4G8lrHZsVxdBeMyPw8/4EnFm307zZbd8LY21byz2K9450mzExLGTx+0AWKQGyygT6PPOXYsNqxC5XEMNZDKTknaGQ1RjiZwRnZAq9quk4KNNmfbgRnuEVKcK0SXeudq3wRwbyA5jT/cYaScfBAdhAgge6tto9aEss+mUEEhm1ZmCxSAfTRKJgE3+ug4npTSSb0KLdGWW4V+ygQ2t+kA9G+1j7U01CGG3jY7aPc/mnJF7Sb2XP0+PNS9eLZpXa6rlJ/1ieMSqppuvvgQgHmKHVs=
        file_glob: true
        file: wheelhouse/sourmash*.whl
        skip_cleanup: true
        on:
          tags: true
    - <<: *wheel
      os: osx
      language: generic
      env:
        - PIP=pip2
stages:
  - check
  - test
  - wheel
