language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"
os: linux
dist: xenial

cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.cargo"
    - "target"
    - ".tox"

branches:
  only:
  - master
  - "/^v.*$/"

script: tox

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustc -V
  - pip install tox-travis

jobs:
  include:
    - &check
      stage: check # do a pre-screen to make sure this is even worth testing
    - &test
      stage: test
    - <<: *test
      os: osx
      language: generic
      before_install:
        - brew update
        - brew outdated python || brew upgrade python
      env:
        - TOXENV=py37
    - <<: *test
      os: linux
      before_install:
        - sudo snap install ipfs
      services:
        - redis-server
        - docker
      before_script:
        - "/snap/bin/ipfs daemon --init --offline &>/dev/null &"
    - &wheel
      stage: build wheel and send to github releases
      services:
        - docker
      env:
        - PIP=pip
        - CIBW_BUILD='cp37-*'
        - CIBW_SKIP='*-manylinux1_i686'
        - CIBW_BEFORE_BUILD_LINUX='source .travis/install_cargo.sh'
        - CIBW_ENVIRONMENT_LINUX='PATH="$HOME/.cargo/bin:$PATH"'
      script:
        - $PIP install cibuildwheel==0.10.0
        - cibuildwheel --output-dir wheelhouse
      deploy:
        provider: releases
        api_key:
          secure: CTO7kiWKLper/nJU093pp796P6MhV2IPz4M2Ws0//YOqU2gKZalyGmAdJtqsFk0+eZthnOp0GQzuSJYpN0+jOx3IU+SInnMg7HdLooyfLxgjDri9xOMBtTiCzSbY77NnLKNk4Nj8idb3Gfjp0F+/5TIRlpInTZ7iYGoG1ZYM/kCyBiTkzDd8tO1LBKhWBad3h3bv099OcmoYT7GETuS9LMmUYJLOe/aotOfOhSttNxYIIIY2RmjFQjWBZCAWPx9P8PnTdhDmrMQL9kRBz+z9/E+ikaaMgtx9QTsF75mZn1qix0+a0LwvRaXKCzYCZ7KGUaSs/npIrBbtXxxA7wK4GFTGb2ERpJOzp4MGzwLiToQlNOHZ48F2N3RgQVL0v+rfvGjt14csWRA21jfrvP2yk4G8lrHZsVxdBeMyPw8/4EnFm307zZbd8LY21byz2K9450mzExLGTx+0AWKQGyygT6PPOXYsNqxC5XEMNZDKTknaGQ1RjiZwRnZAq9quk4KNNmfbgRnuEVKcK0SXeudq3wRwbyA5jT/cYaScfBAdhAgge6tto9aEss+mUEEhm1ZmCxSAfTRKJgE3+ug4npTSSb0KLdGWW4V+ygQ2t+kA9G+1j7U01CGG3jY7aPc/mnJF7Sb2XP0+PNS9eLZpXa6rlJ/1ieMSqppuvvgQgHmKHVs=
        file_glob: true
        file: wheelhouse/sourmash*.whl
        skip_cleanup: true
        on:
          tags: true
    - <<: *wheel
      os: osx
      osx_image: xcode9.2  # Last xcode with support for 10.12 (Sierra)
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD='cp37-*'
stages:
  - check
  - test
  - wheel
