language: python

cache:
  directories:
    - $HOME/.cache/pip

# branches:
#  only:
#  - master
#  - "/^v.*$/"

# only test master and tagged releases on push
# # always test things that aren't pushes (like PRs)
if: type != push OR branch = master

python:
  - "3.7"
#  - "3.6"
#  - "3.5"
#  - "2.7"

dist: xenial

script: tox

install: pip install tox-travis

jobs:
  include:
    - &check
      stage: check # do a pre-screen to make sure this is even worth testing
      os: linux
      python: '3.7'
    - &test
      stage: test
    - <<: *test
      os: osx
      language: generic
      before_install:
        - brew update
        - brew outdated python || brew upgrade python
      env:
        - TOXENV=py37
    - &integration
      stage: integration
      os: linux
      dist: xenial
      python: '3.7'
      install:
        - pip install tox-travis
        - sudo snap install ipfs
      services:
        - redis-server
        - docker
      script:
        - "/snap/bin/ipfs daemon --init --offline &>/dev/null &"
        - tox
    - &wheel
      stage: build wheel and send to github releases
      services:
        - docker
      env:
        - PIP=pip
        - CIBW_SKIP='*-manylinux1_i686'
      script:
        - $PIP install cibuildwheel==0.10.0
        - cibuildwheel --output-dir wheelhouse
      deploy:
        provider: releases
        api_key:
          secure: FjUP0/JguFK6Qg6bx3qhac1qXKEyk/gzZqnDv9esmQw4354NWhOTt/o9f2H7L1M6pr9eEW4n/32lCsXOx6ODvdWW2D+Go8MMoFSnHpwGgmwcUcyy5qaZUiIw84JZEGM0JmKHhcGmfmkxbB3qySiFh5A0Nv+g8gHZsegGV2YImU5j22Hinv+vNpyW/TIBcL9GXp+qiT9kHP/GtcJ6FRz0VV40YNAx6XUG9sxcq1PQ3kjmTH9/WuOg4dyKa49PVcPdAXiE5BdQCLw09a2Lssd1INUNzpe0bg+ttzyre2xtkS/B12tXA752b/l9mUm+Hd1w9oGfmtdy7D76reETelI3VyPizo2IgkTJ7Q1MLyxi00QQFjw8KY90+GQNoMrnAsQk/xD6AYGc9BdkJNipt2Vug8KLZtoU18huaS2220UPFwsOKIDiOccd50e8xu5+UXMUswGYMERpxrE1rzV2ZOpFbBF7xEsqsU28sOJiqxNkC5uHvqG9aYrBIxLu37CKHIMAYkLEsICRNrFrrb4/c3KTvHKmuYY31l+0W6qsJfQCl0QcT1u4m2Dufhyd2Oriue4lTfqIjdVMosy4JrjPBW26XpCRpZIkSLJEMjBbHZplXI02lf/QMABcFbn33VVfeKESlf9tW1Dw9ZQZFAqAqaxKk7bN3CLfARoygTBA7+90COU=
        file_glob: true
        file: wheelhouse/sourmash*.whl
        skip_cleanup: true
        on:
          tags: true
    - <<: *wheel
      os: osx
      language: generic
      env:
        - PIP=pip2
stages:
  - check
  - test
  - integration
  - wheel
