name: asv benchmarks

on:
  push:
    branches: [latest]
  pull_request:
    branches: [latest]
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install asv virtualenv==16.7.9
    - name: Runs benchmarks against latest
      run: |
        asv machine --yes
        asv continuous origin/latest $(git rev-parse HEAD)
